CREATE TABLE demo.persona (
  cod VARCHAR2(4 BYTE) NOT NULL,
  nom VARCHAR2(20 BYTE),
  ape VARCHAR2(20 BYTE),
  CONSTRAINT persona_pk PRIMARY KEY (cod)
);
COMMENT ON COLUMN demo.persona.cod IS 'CLAVE PRINCIPAL';
COMMENT ON COLUMN demo.persona.nom IS 'NOMBRE DE PERSONA';
COMMENT ON COLUMN demo.persona.ape IS 'APELLIDO DE PERSONA';